apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
data:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://auth-api-service"
  
  LOG_CHANNEL: "stack"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"
  
  DB_CONNECTION: "sqlsrv"
  DB_HOST: "sql-server-service"
  DB_PORT: "1433"
  DB_DATABASE: "auth_db"
  
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  FILESYSTEM_DRIVER: "local"
  QUEUE_CONNECTION: "sync"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  
  MEMCACHED_HOST: "127.0.0.1"
  
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: "Laravel"